config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'signup' => 'static_pages#signup'
  get 'registration' => 'users#new'
  get 'login' => 'sessions#new'

  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users do
    member do
      get :clients, :workers
    end
  end
  resources :catalogues do
   collection do
    match 'search' => 'catalogues#search', via: [:get, :post], as: :search
  end
end
resources :tasks do
  resources :responses 
end
resources :responses do
  resources :subcomments
end
resources :appointments
resources :subcomments
resources :educations
resources :offered_services
resources :works
resources :worker_steps
resources :client_steps

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	before_action :restrict_logged_in_user, only: [:signup]
	def home
	end

	def about
	end

	def signup
	end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<div class="center jumbotron">
	<h1>About</h1>
	<h2>
		Instahire
	</h2>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="center jumbotron">
	<h1>Homepage</h1>
	<h2>
		Instahire
		<%= link_to "Catalogue", search_catalogues_path, class: "home_page_links" %>
	</h2>

	<%= search_form_for @search, :defaults => {:required => false}, url: url_for(controller: 'catalogues', action: 'index') do |f| %>

	<%= f.input :subcategory_category_id_eq, label: "Category", collection: Category.order(:name), label_method: :task_name_and_count, value_method: :id, include_blank: "All categories ", :input_html => { id: "hell"} %>
	<%= link_to "Education", "#edu", :id => "edu"%>
	<%=link_to("Edu", "http://localhost:3000/catalogues?utf8=%E2%9C%93&q[subcategory_category_id_eq]=1&commit=Search") %>

<%=link_to 'January', search_catalogues_path(:'q[subcategory_category_id_eq]' => '3'), :id => "edu"%>


	<%=f.submit%>
	<% end %>
</div>

app/views/static_pages/signup.html.erb
<% provide(:title, "Sign up") %>

<div class="jumbotron text-center col-md-6">
	<h1>I want to hire
	</h2>
	<%= link_to "Client Registration", registration_path(:client_value => "true"), class: "btn btn-success btn-lg" %>
</div> 

<div class="jumbotron text-center col-md-6">
	<h1>I want to work
	</h2>
	<%= link_to "Worker Registration", registration_path(:client_value => "false"), class: "btn btn-primary btn-lg" %>
</div>