config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'signup' => 'static_pages#signup'
  get 'registration' => 'users#new'
  get 'login' => 'sessions#new'

  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users do
    member do
      get :clients, :workers
    end
  end
  resources :catalogues do
   collection do
    match 'search' => 'catalogues#search', via: [:get, :post], as: :search
  end
end
resources :tasks do
  resources :responses 
end
resources :responses do
  resources :subcomments
end
resources :appointments
resources :subcomments
resources :educations
resources :offered_services
resources :works
resources :worker_steps
resources :client_steps

end

app/models/task.rb
class Task < ActiveRecord::Base
	#VIRTUAL ATTRIBUTES
	attr_accessor :category_id
	attr_accessor :county_id
	cattr_accessor :current

	#RELATIONSHIPS
	belongs_to :client, class_name: "User"
	belongs_to :worker, class_name: "User"
	belongs_to :area
	delegate :county, :to => :area
	belongs_to :subcategory
	delegate :category, :to => :subcategory
	has_many :appointments, :dependent => :destroy
	has_many :responses, dependent: :destroy
	accepts_nested_attributes_for :appointments, allow_destroy: true

	#VALIDATIONS
	#category validation
	validates :category_id, presence: {message: "Please select a category." } 

	#subcategory validation
	validates :subcategory_id, presence: {message: "Please select a subcategory." }, 
	:if => lambda { |o| o.category_id.present?}

	#title validations
	validates :title, presence: {message: "Please enter a title." }
	validates :title, length: {minimum: 10, maximum: 40, too_short: "Please enter at least 10 characters.", 
		too_long: "Please enter less than 40 characters"}, :if => lambda { |o| o.title.present?}

	#description validations
	validates :description, presence: {message: "Please enter a description." }
	validates :description, length: {minimum: 20, maximum: 200, too_short: "Please enter at least 20 characters.", 
		too_long: "Please enter less than 200 characters."}, 
		:if => lambda { |o| o.description.present?}

	#county validation
	validates :county_id, presence: {message: "Please enter a county." }

	#area validation
	validates :area_id, presence: {message: "Please enter an area." }, 
	:if => lambda { |o| o.county_id.present?}

	#pay offer validation
	validate :pay_offer_validation

	#order tasks: recently added
	default_scope -> { order('created_at DESC') }

	#custom validation
	def pay_offer_validation
		if self.pay_offer.blank?
			errors.add(:pay_offer, "Please enter a value.")
		elsif !self.pay_offer.is_a? Numeric
			errors.add(:pay_offer, "Please enter numeric characters only.")
		else
			if self.is_pay_per_hour
				if self.pay_offer < 10
					errors.add(:pay_offer, "€ #{pay_offer} is invalid. The minimum offer you can set is €10.")
				end
			else
				if self.pay_offer < 20
					errors.add(:pay_offer, "€ #{pay_offer} is invalid. The minimum offer you can set is €20.")
				end
			end
		end
	end

	def title_validation
		if title.blank?
			errors.add(:title, "Please enter a title.")
		end
		if title.present? && title.length < 10
			errors.add(:title, "Minimum is 10")
		end
	end



end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

	before_action :logged_in_user_worker, only: [:new] #worker will not be able to acces tasks/new

	def new
		@task = current_user.task_posts.build
		@task.appointments.build
	end

	def create
		@task = current_user.task_posts.build(task_params)
		if @task.save
			flash[:success] = "Task created!"
			redirect_to @task
		else
			render 'new'
		end
	end

	def edit

		@task = Task.find(params[:id])
		@task.county_id = @task.county.id
		@task.category_id = @task.category.id

	end

	def update
		@task = Task.find(params[:id])

		if @task.update_attributes(task_params)
			flash[:success] = "Task updated"
			redirect_to @task
		else
			render 'edit'
		end
	end

	def show
		@task = Task.find(params[:id])
		@responses = @task.responses.all
		@current_appointment = @task.appointments.first
		@expiry_time = @current_appointment.start_at - 3.hours
		@current_time = Time.zone.now + 1.hours

		@responses.each do |r|
			if r.is_accepted == true
				@accepted_offer = r
				break
			end
		end

	end

	private
	def task_params
		params.require(:task).permit(:category_id, :subcategory_id, :title, :description, :pay_offer, :is_pay_per_hour, :county_id, :area_id, 
			appointments_attributes: [:id, :start_date, :start_time, :duration] )
	end

	def logged_in_user_worker
		unless current_user.client?
			redirect_to(root_url)
		end
	end

end

app/helpers/tasks_helper.rb
module TasksHelper

	

end

app/views/tasks/_appointed_worker.html.erb
<!-- APPOINTED WORKER -->
<% if accepted_offer.nil? %>
<ul class="list-group">
	<li class="list-group-item list-group-item-success"><p2>PAY OFFER: &nbsp; <strong>€<%= task.pay_offer%> <%= task.is_pay_per_hour ? " per hour": "(Fixed pay)"%></strong></p2></li>
</ul>
This task has no worker yet.
<br><br>

<!-- if accepted offer is not nil, there is a worker for this task already -->
<% else %>
<ul class="list-group">
	<li class="list-group-item list-group-item-danger"><del><p2>PAY OFFER: &nbsp; <strong>€<%= task.pay_offer%> <%= task.is_pay_per_hour ? " per hour": "(Fixed pay)"%></strong></p2></del></li>
	<li class="list-group-item list-group-item-success"><p2>PAY AGREEMENT: &nbsp; <strong>€<%= accepted_offer.negotiate_pay %> <%= task.is_pay_per_hour ? " per hour": "(Fixed pay)"%></strong></p2> <br> <%= accepted_offer.comment_text %></li>
</ul>

<div class="row">
	<div class="col-sm-4">
		<% if task.client.picture? %>
		<%= image_tag accepted_offer.user.picture_url, :size => "180x180", class: "img-thumbnail", :id => "prof_pic"  %>
		<% else %>
		<%= image_tag 'default.jpg', :size => "180x180", class: "img-thumbnail"  %>	
		<% end %>
	</div>

	<div class="col-sm-8">
		<h5><span class="glyphicon glyphicon-ok"></span> Accepted Worker: </h5> <h4><%= task.worker.fullname %></h4>

	</div>
</div>

<br>

<% end %>

app/views/tasks/_appointment_form.html.erb
<%= f.input :start_date, label: "Start date", wrapper: :horizontal_input_group do %>
<%= f.input_field :start_date, placeholder: 'Set ', class: "form-control date start" %><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
<% end %>

<%= f.input :start_time, label: "Start time", wrapper: :horizontal_input_group do %>
<%= f.input_field :start_time, placeholder: 'Starting time at', as: :string, class: "form-control time start" %><span class="input-group-addon"><span class="glyphicon glyphicon-time"></span></span>
<% end %>

<%= f.input :duration, label: "Duration", wrapper: :horizontal_input_group  do %>
<%= f.input_field :duration, placeholder: 'Duration', as: :integer, class: "form-control", min: "1", max: "8"%>
<span class="input-group-addon" id="hour-addon">Hour(s)</span>
<% end %>

app/views/tasks/_confirm_completion.html.erb
<div class="row">
	<div class="col-sm-12">
		<div class="panel panel-default">

			<!-- HEADING -->
			<div class="panel-heading">

				<h2><strong>&nbsp;What do you want to do?</strong></h2>

			</div>

			<div class="panel-body">
				<%= link_to new_appointment_path, class: "btn btn-md btn-success pull-left" do %> 
				<i class="glyphicon glyphicon-plus"></i>&nbsp; New Appointment
				<% end %>

				<%= link_to new_appointment_path, class: "btn btn-md btn-danger pull-right" do %> 
				<i class="glyphicon glyphicon-exclamation-sign"></i>&nbsp; Close task
				<% end %>
			</div>
		</div>
	</div>
</div>

<div class="panel panel-default">

	<!-- HEADING -->
	<div class="panel-heading">

		<h2><strong>&nbsp; Recent Appointment </strong></h2>

	</div>
	
	<div class="panel-body">

		<!-- if fixed pay -->
		<% if !task.is_pay_per_hour %>

		<div class="row">

			<div class="col-sm-5">
				<h5>Date:</h5>
			</div>

			<div class="col-sm-7">
				<h4><%= task.appointments.first.start_at.strftime("%d %B, %Y")%></h4>
			</div>

			<div class="col-sm-5">
				<h5>Day:</h5>
			</div>

			<div class="col-sm-7">
				<h4><%= task.appointments.first.start_at.strftime("%A")%></h4>
			</div>

			<div class="col-sm-5">
				<h5>Start time:</h5>
				
			</div>

			<div class="col-sm-7">
				<h4><%= task.appointments.first.start_at.strftime("%I:%M %p")%></h4>
			</div>

		</div>

		<!-- if pay per hour -->
		<% else %>

		<!-- if start date and end date is the same -->
		<% if task.appointments.first.start_at.day == task.appointments.first.end_at.day %>

		<div class="row">
			<div class="col-sm-5">
				<h5>Date:</h5>
			</div>

			<div class="col-sm-7">
				<h4><%= task.appointments.first.start_at.strftime("%d %B, %Y")%></h4>
			</div>

			<div class="col-sm-5">
				<h5>Day:</h5>
			</div>

			<div class="col-sm-7">
				<h4><%= task.appointments.first.start_at.strftime("%A")%></h4>
			</div>

			<div class="col-sm-5">
				<h5>Start time:</h5>
				
			</div>

			<div class="col-sm-7">
				<h4><%= task.appointments.first.start_at.strftime("%I:%M %p")%></h4>
			</div>

			<% if task.is_pay_per_hour %>
			<div class="col-sm-5">
				<h5>End time:</h5>
			</div>

			<div class="col-sm-7">
				<h4><%= task.appointments.first.end_at.strftime("%I:%M %p")%></h4>
			</div>
			<% end%>		
		</div>

		<% else %>

		<!-- if start date and end date is different -->
		<div class="row">
			<div class="col-sm-5">
				<h5>Start Date:</h5>
			</div>

			<div class="col-sm-7">
				<h4><%= task.appointments.first.start_at.strftime("%d %B, %Y")%></h4>
			</div>

			<div class="col-sm-5">
				<h5>Day:</h5>
			</div>

			<div class="col-sm-7">
				<h4><%= task.appointments.first.start_at.strftime("%A")%></h4>
			</div>

			<div class="col-sm-5">
				<h5>Start time:</h5>
				
			</div>

			<div class="col-sm-7">
				<h4><%= task.appointments.first.start_at.strftime("%I:%M %p")%></h4>
			</div>

			<div class="col-sm-12">
				<hr>
			</div>

			<div class="col-sm-5">
				<h5>End Date:</h5>
			</div>

			<div class="col-sm-7">
				<h4><%= task.appointments.first.end_at.strftime("%d %B, %Y")%></h4>
			</div>

			<div class="col-sm-5">
				<h5>Day:</h5>
			</div>

			<div class="col-sm-7">
				<h4><%= task.appointments.first.end_at.strftime("%A")%></h4>
			</div>


			<% if task.is_pay_per_hour %>
			<div class="col-sm-5">
				<h5>End time:</h5>
			</div>

			<div class="col-sm-7">
				<h4><%= task.appointments.first.end_at.strftime("%I:%M %p")%></h4>
			</div>
			<% end%>		
		</div>


		<% end %> <!-- end if else same day-->

		<% end %> <!-- end if else pay_per_hour-->


		<%= link_to edit_appointment_path(task.appointments.first.id), class: "btn btn-md btn-success pull-left" do %> 
		<i class="glyphicon glyphicon-pencil"></i>&nbsp; Rate and leave feedback
		<% end %>

	</div>
</div>

app/views/tasks/_expired_task_appointment.html.erb
Expired!

Renew

<div class="panel panel-default">

	<!-- HEADING -->
	<div class="panel-heading">

		<h2 class ="pull-left"><strong><i class="glyphicon glyphicon-exclamation-sign"></i>&nbsp;Your appointment has expired</strong></h2>

	</div>

	<div class="panel-body">
		<%= link_to new_appointment_path, class: "btn btn-md btn-success pull-left" do %> 
		<i class="glyphicon glyphicon-plus"></i>&nbsp; New Appointment
		<% end %>

	
	</div>
</div>

app/views/tasks/_in_progress_appointment.html.erb
<div class="panel panel-default">

	<!-- HEADING -->
	<div class="panel-heading">

		<h2><strong><i class="glyphicon glyphicon-exclamation-sign"></i>&nbsp; Happening now!</strong></h2>

		<!-- EDIT LINK -->
		<!-- it will be only shown to the client of this task -->
		<% if current_user?(task.client) %>
		<%= link_to edit_appointment_path(task.appointments.first.id), class: "pull-right edit-appointment" do %> 
		<i class="glyphicon glyphicon-pencil"></i>&nbsp; Edit
		<% end %>
		<% end %>

	</div>
	
	<div class="panel-body">

		<!-- if fixed pay -->
		<% if !task.is_pay_per_hour %>

		<div class="row">

			<div class="col-sm-5">
				<h5>Date:</h5>
			</div>

			<div class="col-sm-7">
				<h4><%= task.appointments.first.start_at.strftime("%d %B, %Y")%></h4>
			</div>

			<div class="col-sm-5">
				<h5>Day:</h5>
			</div>

			<div class="col-sm-7">
				<h4><%= task.appointments.first.start_at.strftime("%A")%></h4>
			</div>

			<div class="col-sm-5">
				<h5>Start time:</h5>
				
			</div>

			<div class="col-sm-7">
				<h4><%= task.appointments.first.start_at.strftime("%I:%M %p")%></h4>
			</div>

		</div>

		<!-- if pay per hour -->
		<% else %>

		<!-- if start date and end date is the same -->
		<% if task.appointments.first.start_at.day == task.appointments.first.end_at.day %>

		<div class="row">
			<div class="col-sm-5">
				<h5>Date:</h5>
			</div>

			<div class="col-sm-7">
				<h4><%= task.appointments.first.start_at.strftime("%d %B, %Y")%></h4>
			</div>

			<div class="col-sm-5">
				<h5>Day:</h5>
			</div>

			<div class="col-sm-7">
				<h4><%= task.appointments.first.start_at.strftime("%A")%></h4>
			</div>

			<div class="col-sm-5">
				<h5>Start time:</h5>
				
			</div>

			<div class="col-sm-7">
				<h4><%= task.appointments.first.start_at.strftime("%I:%M %p")%></h4>
			</div>

			<% if task.is_pay_per_hour %>
			<div class="col-sm-5">
				<h5>End time:</h5>
			</div>

			<div class="col-sm-7">
				<h4><%= task.appointments.first.end_at.strftime("%I:%M %p")%></h4>
			</div>
			<% end%>		
		</div>

		<% else %>

		<!-- if start date and end date is different -->
		<div class="row">
			<div class="col-sm-5">
				<h5>Start Date:</h5>
			</div>

			<div class="col-sm-7">
				<h4><%= task.appointments.first.start_at.strftime("%d %B, %Y")%></h4>
			</div>

			<div class="col-sm-5">
				<h5>Day:</h5>
			</div>

			<div class="col-sm-7">
				<h4><%= task.appointments.first.start_at.strftime("%A")%></h4>
			</div>

			<div class="col-sm-5">
				<h5>Start time:</h5>
				
			</div>

			<div class="col-sm-7">
				<h4><%= task.appointments.first.start_at.strftime("%I:%M %p")%></h4>
			</div>

			<div class="col-sm-12">
				<hr>
			</div>

			<div class="col-sm-5">
				<h5>End Date:</h5>
			</div>

			<div class="col-sm-7">
				<h4><%= task.appointments.first.end_at.strftime("%d %B, %Y")%></h4>
			</div>

			<div class="col-sm-5">
				<h5>Day:</h5>
			</div>

			<div class="col-sm-7">
				<h4><%= task.appointments.first.end_at.strftime("%A")%></h4>
			</div>


			<% if task.is_pay_per_hour %>
			<div class="col-sm-5">
				<h5>End time:</h5>
			</div>

			<div class="col-sm-7">
				<h4><%= task.appointments.first.end_at.strftime("%I:%M %p")%></h4>
			</div>
			<% end%>		
		</div>


		<% end %> <!-- end if else same day-->

		<% end %> <!-- end if else pay_per_hour-->

	</div>
</div>

app/views/tasks/_question_negotiation_form.html.erb
<!-- question and negotiation section -->
<div class="col-md-12">

	<!-- SWITCH BUTTONS -->
	<!-- if client, response form will be hidden, else if worker, it will be shown -->
	<% if !current_user.client? %>
	<div class="row">
		<div class="col-md-6 ">

			<%= link_to "switch", task_path(:is_comment => "false"), class: "btn btn-success btn-lg", id: "switch-collapse", remote: true %>
			<%= link_to "Ask a question", task_path(:is_comment => true), class: "btn btn-success btn-lg", id: "ask-question", :data => { :toggle => 'collapse', :target => '#response-form' }, remote: true %> 
			<%= link_to "Negotiate pay", task_path(:is_comment => false), class: "btn btn-success btn-lg pull-right", id: "negotiate", :data => { :toggle => 'collapse', :target => '#response-form' }, remote: true %>
		</div>
	</div>
	<br><br>
	<% end %> <!--// if !current_user.client?  -->


	<!-- RESPONSE FORM: negotiation or question -->
	<div id="response-form" class="collapse">
		<%= simple_form_for ([task, Response.new]) do |f| %>
		<%= f.input :is_comment, as: :hidden %>

		<div class="row">

			<!-- CURRENT USER'S DISPLAY PICTURE -->
			<div class="col-md-2">
				<% if current_user.picture? %>
				<%= image_tag current_user.picture_url(:thumb), class: "img-thumbnail", :id => "prof_pic"  %>
				<% else %>
				<%= image_tag 'default.jpg', :size => "100x100", class: "img-thumbnail"  %>	
				<% end %>
			</div>

			<!-- NEGOTIATION FORM -->
			<div class="col-md-10">			
				<div class="row" id="negotiate-field">	
					<%= f.input :negotiate_pay, wrapper: :horizontal_input_group, label: false do %>
					<span class="input-group-addon">€</span>
					<%= f.input_field :negotiate_pay, as: :integer, class: "form-control", min: task.pay_offer, step: '1', value: task.pay_offer %>
					<span class="input-group-addon">Euro</span>
					<% end %>
					<span class="glyphicon glyphicon-question-sign extra-negotiation-info"
					data-toggle="popover" data-placement="left" data-original-title="Negotiate pay amount" data-content="You can only match the pay offer of the client or demand a pay increase. The pay type is only decided by the client. If you wish to change the pay type, you can make a request on ask a question form."></span>
					<br>
					<!-- the negotiation pay hint is changing dynamically -->
					<p id="negotiation_pay_hint" class="help-block">#</p>
				</div>

				<span class="glyphicon glyphicon-question-sign extra-info pull-right"
				data-toggle="popover" data-placement="left" data-original-title="Condition/ comment" data-content="You can include a comment or make a condition that comes together with your suggested ideal pay amount."></span>
				<%= f.input :comment_text, as: :text, input_html: {rows: 3}, label: false %>

				<p id="comment_text_hint"class="help-block"></p>

				<div class="row"> 
					<div class="col-md-4 col-md-offset-8">
						<%= f.button :submit, id: "create_response_button" %>
					</div>
				</div>

				<% end %><!--  negotiate form -->
			</div>
		</div>
	</div>


	<br>
</div>
<!--// question and negotiation section -->

app/views/tasks/_task_info.html.erb
<!-- diplay picture -->
<div class="col-sm-3">
	<% if task.client.picture? %>
	<%= image_tag @task.client.picture_url, :size => "180x180", class: "img-thumbnail", :id => "prof_pic"  %>
	<% else %>
	<%= image_tag 'default.jpg', :size => "180x180", class: "img-thumbnail"  %>	
	<% end %>
</div>

<div class="col-sm-9">
	<div class="row">
		<div class="col-sm-12">
			<h1> <%= task.title %> </h1> 	
			<%= "updated #{customised_time_ago_in_words(task.updated_at)} ago |" if  task.updated_at != task.created_at %> <%= "created #{customised_time_ago_in_words(task.created_at)} ago" %>

			<% if current_user?(task.client) %>
			<%= link_to edit_task_path(task.id), class: "pull-right" do %>
			<i class="glyphicon glyphicon-pencil"></i>&nbsp Edit Task
			<% end %>
			<% end %>


		</div>		
	</div><hr>

	<div class="row">
		<div class="col-sm-3">
			Client
		</div>
		<div class="col-sm-9">
			<%= task.client.fullname%>
		</div>		

	</div><br>

	<div class="row">
		<div class="col-sm-3">
			Location:
		</div>
		<div class="col-sm-9">
			<%= task.area.name%> <%= task.area.county.name%>
		</div>		

	</div><br>

	<div class="row">
		<div class="col-sm-3">
			Category:
		</div>
		<div class="col-sm-9">
			<%= task.subcategory.category.name%>
		</div>		

	</div><br>

	<div class="row">
		<div class="col-sm-3">
			Subcategory:
		</div>
		<div class="col-sm-9">
			<%= task.subcategory.name%>
		</div>		
	</div>

</div>	<!--// col 9 -->

app/views/tasks/_upcoming_appointment.html.erb
<div class="panel panel-default">

	<!-- HEADING -->
	<div class="panel-heading">

		<h2 class ="pull-left"><strong><i class="glyphicon glyphicon-exclamation-sign"></i>&nbsp;Upcoming Appointment</strong></h2>

		<!-- edit link -->
		<!-- it will be only shown to the client of this task -->
		<% if current_user?(task.client) %>
		<%= link_to edit_appointment_path(task.appointments.first.id), class: "pull-right edit-appointment" do %> 
		<i class="glyphicon glyphicon-pencil"></i>&nbsp; Edit
		<% end %>
		<% end %>

	</div>
	
	<div class="panel-body">

		<!-- if fixed pay -->

		<% if !task.is_pay_per_hour %>

		<div class="row">
			<div class="col-sm-5">
				<h5>Date:</h5>
			</div>

			<div class="col-sm-7">
				<h4><%= task.appointments.first.start_at.strftime("%d %B, %Y")%></h4>
			</div>

			<div class="col-sm-5">
				<h5>Day:</h5>
			</div>

			<div class="col-sm-7">
				<h4><%= task.appointments.first.start_at.strftime("%A")%></h4>
			</div>

			<div class="col-sm-5">
				<h5>Start time:</h5>
				
			</div>

			<div class="col-sm-7">
				<h4><%= task.appointments.first.start_at.strftime("%I:%M %p")%></h4>
			</div>

		</div>

		<!-- if pay per hour -->

		<% else %>

		<!-- if start date and end date is the same -->

		<% if task.appointments.first.start_at.day == task.appointments.first.end_at.day %>

		<div class="row">
			<div class="col-sm-5">
				<h5>Date:</h5>
			</div>

			<div class="col-sm-7">
				<h4><%= task.appointments.first.start_at.strftime("%d %B, %Y")%></h4>
			</div>

			<div class="col-sm-5">
				<h5>Day:</h5>
			</div>

			<div class="col-sm-7">
				<h4><%= task.appointments.first.start_at.strftime("%A")%></h4>
			</div>

			<div class="col-sm-5">
				<h5>Start time:</h5>
				
			</div>

			<div class="col-sm-7">
				<h4><%= task.appointments.first.start_at.strftime("%I:%M %p")%></h4>
			</div>

			<% if task.is_pay_per_hour %>
			<div class="col-sm-5">
				<h5>End time:</h5>
			</div>

			<div class="col-sm-7">
				<h4><%= task.appointments.first.end_at.strftime("%I:%M %p")%></h4>
			</div>
			<% end%>		
		</div>

		<% else %>

		<!-- if start date and end date is different -->

		<div class="row">
			<div class="col-sm-5">
				<h5>Start Date:</h5>
			</div>

			<div class="col-sm-7">
				<h4><%= task.appointments.first.start_at.strftime("%d %B, %Y")%></h4>
			</div>

			<div class="col-sm-5">
				<h5>Day:</h5>
			</div>

			<div class="col-sm-7">
				<h4><%= task.appointments.first.start_at.strftime("%A")%></h4>
			</div>

			<div class="col-sm-5">
				<h5>Start time:</h5>
				
			</div>

			<div class="col-sm-7">
				<h4><%= task.appointments.first.start_at.strftime("%I:%M %p")%></h4>
			</div>

			<div class="col-sm-12">
				<hr>
			</div>

			<div class="col-sm-5">
				<h5>End Date:</h5>
			</div>

			<div class="col-sm-7">
				<h4><%= task.appointments.first.end_at.strftime("%d %B, %Y")%></h4>
			</div>

			<div class="col-sm-5">
				<h5>Day:</h5>
			</div>

			<div class="col-sm-7">
				<h4><%= task.appointments.first.end_at.strftime("%A")%></h4>
			</div>


			<% if task.is_pay_per_hour %>
			<div class="col-sm-5">
				<h5>End time:</h5>
			</div>

			<div class="col-sm-7">
				<h4><%= task.appointments.first.end_at.strftime("%I:%M %p")%></h4>
			</div>
			<% end%>		
		</div>


		<% end %> <!-- end if else same day-->

		<% end %> <!-- end if else pay_per_hour-->

	</div>
</div>

app/views/tasks/edit.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<div class="panel panel-default main-panel">

			<div class="panel-heading widen-main-panel-heading">
				<h2 class="alignleft"><strong>Edit task details</strong></h2>
			</div> 

			<%= render 'task_form', task: @task, is_new: false %>

		</div>
	</div>
</div>

app/views/tasks/new.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<div class="panel panel-default main-panel">

				<%= render 'task_form', task: @task, is_new: true %>

		</div>
	</div>
</div>