config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'signup' => 'static_pages#signup'
  get 'registration' => 'users#new'
  get 'login' => 'sessions#new'

  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users do
    member do
      get :clients, :workers
    end
  end
  resources :catalogues do
   collection do
    match 'search' => 'catalogues#search', via: [:get, :post], as: :search
  end
end
resources :tasks do
  resources :responses 
end
resources :responses do
  resources :subcomments
end
resources :appointments
resources :subcomments
resources :educations
resources :offered_services
resources :works
resources :worker_steps
resources :client_steps

end

app/models/user.rb
class User < ActiveRecord::Base
	#ATTRIBUTES
	attr_accessor :remember_token
	attr_accessor :county_id

	mount_uploader :picture, PictureUploader

	#RELATIONSHIPS
	belongs_to :area
	delegate :county, :to => :area

	has_many :task_posts, class_name: "Task", foreign_key: "client_id", dependent: :destroy
	has_many :task_todos, class_name: "Task", foreign_key: "worker_id", dependent: :destroy

	has_many :workers, through: :task_posts, source: :worker
	has_many :clients, through: :task_todos, source: :client

	has_many :educations, dependent: :destroy
	has_many :works, dependent: :destroy
	has_many :offered_services, dependent: :destroy
	has_many :responses
	has_many :subcomments

	accepts_nested_attributes_for :educations, allow_destroy: true
	accepts_nested_attributes_for :works, allow_destroy: true
	accepts_nested_attributes_for :offered_services, allow_destroy: true

	#VALIDATIONS
	before_save {self.email = email.downcase}
	validates :first_name, presence: {message: "Please enter your first name." }, length: {maximum: 25}
	validates :last_name, presence: {message: "Please enter your last name." }, length: {maximum: 25}

	# Email validations
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: {message: "Please enter an email." }, length: {maximum: 50}
	validates :email, format: {with: VALID_EMAIL_REGEX, :message => "Invalid! Please enter a valid email."},
	:if => lambda { |o| o.email.present?}
	validates :email, uniqueness: { case_sensitive: false, :message => "This email has already been taken." } 


	# Password validations
	has_secure_password
	validates :password, length: { minimum: 6 }, allow_blank: true

	# Location validations
	# validates :county_id, presence: true, :if => lambda { self.created_at?}
	# validates :area_id, presence: true, :if => lambda { |o| o.county_id.present?}

	# Personal bio validation
	validates :personal_bio, length: {maximum: 50}

	

	# Class method


	#used in select dropdown is_pay_per_hour input
	HASH_NAME = {
		"Pay per hour" => "Pay per hour",
		"Fixed pay" => "Fixed pay",
	}

	
	def fullname
		"#{first_name} #{last_name}".titleize
	end

	def role
		if self.client
			"Client"
		else
			"Worker"
		end
	end

	def location
		"#{self.area.name}, #{self.county.name}"
	end

	def User.new_token
		SecureRandom.urlsafe_base64
	end

	# Returns the hash digest of the given string.
	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
		BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end

	# Remembers a user in the database for use in persistent sessions.
	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(remember_token))
	end

	# Returns true if the given token matches the digest.
	def authenticated?(remember_token)
		return false if remember_digest.nil?
		BCrypt::Password.new(remember_digest).is_password?(remember_token)
	end

	# Forgets a user.
	def forget
		update_attribute(:remember_digest, nil)
	end

	

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	#FILTERS
	before_action :logged_in_user, only: [:index, :edit, :update]
	before_action :restrict_logged_in_user, only: [:new] #logged in users will not be able to access registration page
	before_action :correct_user, only: [:edit, :update]	#correct users will not be able to edit or update other's profile
	

	def destroy
		User.find(params[:id]).destroy
		flash[:success] = "User deleted"
		redirect_to users_url
	end

	def index
		# @users = User.all
		@users = User.where(:client => false).paginate(page: params[:page], :per_page => 5)
	end

	def new
		if params[:client_value] == nil
			render 'static_pages/signup'
		end
		
		@user = User.new
		session[:isClient] = params[:client_value]
		@user.client = session[:isClient]
		# @user.educations.build
	end

	def create
		@user = User.new(user_params)
		if @user.save
			log_in @user
			# if @user.client 
			# 	flash[:success] = "Welcome to Instahire! You are now a registered client."
			# else
			# 	flash[:success] = "Welcome to Instahire! You are now a registered worker."
			# end
			if @user.client == true 
				redirect_to client_steps_path
			else
				flash[:success] = "Thank you for registering! Please complete the following steps"
				redirect_to worker_steps_path
			end
		else
			render 'new'
		end
	end

	def show
		@user = User.find(params[:id])
		@skills = @user.offered_services.paginate page: params[:page], per_page: 3
		@educations = @user.educations.paginate page: params[:page], per_page: 4
		@works = @user.works.paginate page: params[:page], per_page: 4
		# @search = @user.task_posts.search(params[:q])
		# @search = Task.all.search(params[:q])
		@task_posts = @user.task_posts
	end

	def update
		@user = User.find(params[:id])

		if @user.update_attributes(user_params)
			flash[:success] = "Profile updated"
			redirect_to @user
		else
			render 'edit'
		end
	end

	def edit
		@user = User.find(params[:id])
		# @user.county_id = @user.area.county_id
		# if @user.county_id.present?
		# 	@user.county_id = @user.county.id
		# end
	end

	private
# Before filters

# Confirms a logged-in user.
# Users who are not logged in will not have an access to index, edit, and update actions
def logged_in_user
	unless logged_in?
		store_location
		flash[:danger] = "Please log in."
		redirect_to login_url
	end
end



# Confirms the correct user.
# Correct user will not have access to edit and update other users.
# Correct user will only have access to edit and update their own.
def correct_user
	@user = User.find(params[:id])
	redirect_to(root_url) unless current_user?(@user)
end

end

app/helpers/users_helper.rb
module UsersHelper

	def display_header(isClient)
		if isClient
			"CLIENT REGISTRATION"
		else
			"WORKER REGISTRATION"
		end
	end

	def gravatar_for(user, options = { size: 80 })
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.first_name, class: "gravatar")
	end
end

app/views/users/_client_tabs.html.erb
	<!-- TABS -->
	<ul class="nav nav-tabs nav-justified" id="myTab">

		<!-- Profile tab -->
		<li class="<%= 'active' if params[:tab] == 'profile' || !params[:tab] %>">
			<a href="#task" data-toggle="tab">Task</a>
		</li>

		<!-- Appointment tab -->
		<li>
			<a href="#appointment" data-toggle="tab">Appointment </a>
		</li>

		<!-- Appointment tab -->
		<!-- li class="dropdown">
			<a href="#" data-toggle="dropdown">Appointments<span class="caret"></span></a>
			<ul class="dropdown-menu" role="menu">
				<li><a href="#tab4primary" data-toggle="tab">Upcoming</a></li>
				<li><a href="#tab5primary" data-toggle="tab">In Progress</a></li>
				<li><a href="#tab5primary" data-toggle="tab">Completed</a></li>
				<li><a href="#tab5primary" data-toggle="tab">Cancelled</a></li>
			</ul>
		</li> -->
	</ul>
	<!--// Tabs -->


	<!-- TAB CONTENTS -->
	<div class="tab-content">

		<!-- PROFILE CONTENT --> <!-- this tab will be active on page load -->
		<div class="<%= if (params[:tab] == 'task' || !params[:tab]) then 'tab-pane active'  else 'tab-pane' end %>" id="task">
			<%= (render 'tab_task')%>
			<hr>
		</div>

		<!-- Requests content -->
		<div class="tab-pane" id="appointment">
			ssdsd
		</div>
		<!--// Requests content -->

	</div>
		<!--// Tab contents -->

app/views/users/_display_profile_sections.html.erb
<!-- DISPLAY SKILLS -->
<% if user.offered_services.any? %>
<div class="panel panel-default sub-panel-profile">
	<span>
		<row>
			<%= image_tag 'skill.png', :size => "60x60" , class: "pull-left profile-icon "%>
			<h3>&nbsp; Skill (Offered Service) <span class="badge display-count"><%= user.offered_services.count %></span></h3>
			<%= link_to edit_offered_service_path(current_user), class: "pull-right edit-profile-link" do %>
			<i class="glyphicon glyphicon-pencil"></i>&nbsp; Edit or Add
			<% end %>
		</span>
		<hr>
		<div id= "skill_sections">
			<%= render 'skill_section', skills: @skills %>
		</div>
	</div>
	<% end %>

	<!-- DISPLAY EDUCATIONS -->
	<% if user.educations.any? %>
	<div class="panel panel-default sub-panel-profile">
		<span>
			<%= image_tag 'education.png', :size => "60x60" , class: "pull-left profile-icon "%>
			<h3>&nbsp; Education Qualification <span class="badge display-count"><%= user.educations.count %></span></h3>
			<%= link_to edit_education_path(current_user), class: "pull-right edit-profile-link" do %> 
			<i class="glyphicon glyphicon-pencil"></i>&nbsp Edit or Add
			<% end %>
		</span>

		<hr>

		<div id= "education_sections">
			<%= render 'education_section', educations: @educations %>
		</div>

	</div>
	<% end %>

	<!-- DISPLAY WORK EXPERIENCES -->
	<% if user.works.any? %>
	<div class="panel panel-default sub-panel-profile">
		<%= image_tag 'work.png', :size => "60x60" , class: "pull-left profile-icon "%>
		<h3>&nbsp Work Experience</h3>
		<%= link_to edit_work_path(current_user), class: "pull-right edit-profile-link" do %>
		<i class="glyphicon glyphicon-pencil"></i>&nbspEdit or Add
		<% end %>
		<hr>

		<div id= "work_sections">
			<%= render 'work_section', works: @works %>
		</div>

	</div>
	<% end %>

app/views/users/_education_section.html.erb
<% educations.each do |e| %>

<!-- row -->
<div class="row">

	<!-- SCHOOL NAME -->
	<div class="col-md-12">
		<h5>School Name:&nbsp; </h5> 
		<h4 ><%= e.school_name.split.map(&:capitalize).join(' ') %></h4> 

	</div>

	<!-- QUALIFICATION -->
	<div class="col-md-12">
		<h5>Qualification:&nbsp; </h5> 
		<h4 ><%= e.degree %></h4> 
	</div>

	<!-- TIME PERIOD -->
	<div class="col-md-12">
		<h5>Time period: </h5> 
		<h4><%= e.year_started.strftime("%B %Y") %> - <%= e.year_finished.strftime("%B %Y") %> 
			<%= time_period(e.year_started, e.year_finished) %> 
		</h4>
	</div>

	<hr>

</div>
<!--// row -->

<% end %>

app/views/users/_skill_section.html.erb
<% skills.each do |s| %>
<!-- row -->
<div class="row">

	<!-- SKILL NAME -->
	<div class="col-md-6">
		<h5>Skill Name:&nbsp; </h5> 
		<h4 ><%= s.title %></h4> 
	</div>

	<!-- CATEGORY -->
	<div class="col-md-6">
		<h5>Skill Category:</h5>
		<h4><%= s.subcategory.name%></h4> 

	</div>

	<!-- DESCRIPTION -->
	<div class="col-md-12">
		<h5>Description:</h5>
		<div class="well well-sm">
			<p1 class = "article"><%= s.service_description %></p1>
		</div>
		<hr>
	</div>

</div>
<!--// row -->

<% end %>

<%= will_paginate skills %>

app/views/users/_tab_task.html.erb
<div class="row">

	<div class="col-md-12">
		<!-- tabs left -->
		<div class="tabbable">
			
			<div class="tab-content col-md-10">
				<br>
				<h4>Pending tasks</h4>
				<div class="tab-pane active" id="a">Lorem ipsum dolor sit amet, charetra varius rci quis tortor imperdiet venenatis quam sit amet vulputate. Quisque mauris augue, molestie tincidunt condimentum vitae, gravida a libero.</div>
				<div class="tab-pane" id="b">Secondo sed ac orci quis tortor imperdiet venenatis. Duis elementum auctor accumsan. Aliquam in felis sit amet augue.</div>
				<div class="tab-pane" id="c">Thirdamuno, ipsum dolor sit amet, consectetur adipiscing elit. Duis elementum auctor accumsan. Duis pharetra varius quam sit amet vulputate. Quisque mauris augue, molestie tincidunt condimentum vitae. </div>
			</div>

			<ul class="nav nav-pills nav-stacked col-md-2">
				<li><br><a href="#a" data-toggle="tab">Pending Tasks</a><br></li>
				<li class="active"><a href="#b" data-toggle="tab">Active Tasks</a><br></li>
				<li><a href="#c" data-toggle="tab">Closed Tasks</a><br></li>
			</ul>
		</div>
		<!-- /tabs -->
	</div>



</div>
    <!-- /row -->

app/views/users/_tab_worker_profile.html.erb
<!-- PROFILE TAB for workers -->
<br><br>

<!-- display this in profile tab, if skill(service), education and work are blank -->
<% if @user.offered_services.blank? && @user.educations.blank? && @user.works.blank?%>
<%= render 'empty_profile_sections', user: @user %>
<% end %>

<!-- partial: profile sections. ie: education, skill, work -->
<%= render 'display_profile_sections', user: @user %>

app/views/users/_user.html.erb
<!-- display all users -->
<li>
<%= gravatar_for user, size: 50 %>
<%= link_to user.first_name, user %>
<% if current_user.client? && !current_user?(user) %>
	| <%= link_to "delete", user, method: :delete,
	data: { confirm: "You sure?" } %>
	
	<% end %>
</li>

app/views/users/_work_section.html.erb
<% works.each do |w| %>
<!-- row -->
<div class="row">

	<!-- COMPANY NAME -->
	<div class="col-md-12">
		<h5>Company Name:&nbsp; </h5> 
		<h4><%= w.company_name.split.map(&:capitalize).join(' ')  %></h4>
	</div>

	<!-- WORK TITLE -->
	<div class="col-md-12">
		<h5>Work title/ Position:&nbsp; </h5> 
		<h4><%= w.work_title %></h4>
	</div>

	<!-- TIME PERIOD -->
	<div class="col-md-12">
		<h5>Dates attended:&nbsp; </h5> 
		<% if w.is_currently_working? %>
		<h4><%= w.date_started.strftime("%B %Y") %> - Present  <%= time_period(w.date_started, DateTime.now)%> </h4>
		<% else %>
		<h4><%= w.date_started.strftime("%B %Y") %> - <%= w.date_finished.strftime("%B %Y") %>
			<%= time_period(w.date_started, w.date_finished)%> 
		</h4>
		<% end %>
	</div>


	<hr>
</div>

<% end %>

app/views/users/_worker_tabs.html.erb
	<!-- TABS -->
	<ul class="nav nav-tabs nav-justified" id="myTab">

		<!-- Profile tab -->
		<li class="<%= 'active' if params[:tab] == 'profile' || !params[:tab] %>">
			<a href="#profile" data-toggle="tab">Profile</a>
		</li>

		<!-- Request tab -->
		<li>
			<a href="#requests" data-toggle="tab">Task Requests <%= @user.task_posts.count %> </a>
		</li>

		<!-- Appointment tab -->
		<li class="dropdown">
			<a href="#" data-toggle="dropdown">Appointments<span class="caret"></span></a>
			<ul class="dropdown-menu" role="menu">
				<li><a href="#tab4primary" data-toggle="tab">Upcoming</a></li>
				<li><a href="#tab5primary" data-toggle="tab">In Progress</a></li>
				<li><a href="#tab5primary" data-toggle="tab">Completed</a></li>
				<li><a href="#tab5primary" data-toggle="tab">Cancelled</a></li>
			</ul>
		</li>
	</ul>
	<!--// Tabs -->


	<!-- TAB CONTENTS -->
	<div class="tab-content">

		<!-- PROFILE CONTENT (this tab will be active on page load) --> 
		<div class="<%= if (params[:tab] == 'profile' || !params[:tab]) then 'tab-pane active'  else 'tab-pane' end %>" id="profile">
			<%= (render 'tab_worker_profile') %>
			<hr>
		</div>

		<!-- Requests content -->
		<div class="tab-pane" id="requests">
			ssdsd
		</div>
		<!--// Requests content -->

	</div>
		<!--// Tab contents -->

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<div class="panel panel-default main-panel">

			<div class="panel-heading widen-main-panel-heading">
				<h2 class="alignleft">
					<i class="glyphicon glyphicon-pencil"></i> &nbsp;
					<strong>EDIT PROFILE</strong>
				</h2>
			</div> 

			<%= simple_form_for @user, html: {class: 'form-horizontal'}, wrapper: :horizontal_input_group do |f| %>

			<div class="widen-error">
				<%= render 'shared/error_messages', object: f.object %>
			</div>
			<fieldset>
				<div class="panel panel-default sub-panel">
					<div class="inner-div-panel">

						<!-- UPLOAD SECTION -->
						<%= render 'upload_section', user: @user, f: f %>

						<!-- FIRST NAME -->
						<div class="required-field-block">
							<%= f.input :first_name, :required => false %>
							<div class="required-icon">
								<div class="text">*</div>
							</div>
						</div>

						<!-- LAST NAME -->
						<div class="required-field-block">
							<%= f.input :last_name, :required => false %>
							<div class="required-icon">
								<div class="text">*</div>
							</div>
						</div>

						<!-- EMAIL -->
						<div class="required-field-block">
							<%= f.input :email, :required => false %>
							<div class="required-icon">
								<div class="text">*</div>
							</div>
						</div>

						<!-- CHANGE PASSWORD -->
						<%= f.input :password, label: "Change password" %>

						<!-- CONFIRM PASSWORD -->
						<%= f.input :password_confirmation, label: "Confirm password" %>
							
						<!-- PERSONAL BIO -->
						<%= f.input :personal_bio, as: :text, input_html: {rows: 6}, placeholder: "Enter a summary of yourself. (Sell yourself here.)", hint: "maximum text is 50" %>

						<!-- COUNTY -->
						<div class="required-field-block">
							<div class="required-icon">
								<div class="text">*</div>
							</div>
						</div>
						<%= f.input :county_id, collection: County.order(:name), label_method: :name, value_method: :id, label: "County", include_blank: "Select county where you are located" %>
						
						<!-- AREA -->
						<div class="required-field-block" id="required-area">
							<div class="required-icon">
								<div class="text">*</div>
							</div>
						</div>
						<%= f.input :area_id, collection: County.order(:name), as: :grouped_select, group_method: :areas %>

					</div>
				</div>
			</fieldset>

			<!-- submit button -->
			<div class="row">
				<div class="col-md-3 col-md-offset-9">
					<%= f.button :submit, "Update Profile", class: "btn btn-success btn-md submit-button" %>
				</div>
			</div>
			<!--// submit button -->

			<% end %>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All workers</h1>

<%= will_paginate %>
<ul class="users">
	<%= render @users %>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, "Registration") %>
<br><br>
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<div class="panel panel-default main-panel">

			<!-- worker registration or client registration -->
			<div class="panel-heading widen-main-panel-heading">				
				<h2 class="alignleft"><strong><%= display_header(@user.client)%></strong></h2>	
			</div>

			<%= simple_form_for @user, html: {class: 'form-horizontal'}, wrapper: :horizontal_input_group do |f| %>

			<%# Error message heading%>
			<div class="widen-error">
				<%= render 'shared/error_messages', object: f.object %>
			</div>
			<%# END: Error message heading%>

			<fieldset>
				<div class="panel panel-default sub-panel">
					<div class="inner-div-panel">
						<%= f.input :first_name %>
						<%= f.input :last_name %>
						<%= f.input :email %>
						<%= f.input :password %>
						<%= f.input :password_confirmation, label: "Confirm password"  %>
						<%= f.input :client, as: :hidden %>
					</div>
				</div>
			</fieldset>
			
			<div class="row">
				<div class="col-md-3 col-md-offset-9">
					<%= f.button :submit, "Join Instahire", class: "btn btn-success btn-md submit-button" %>
				</div>
			</div>

			<% end %>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.first_name) %>

<!-- Row -->
<div class="row">

	<!-- Side dashboard -->
	<%= render 'side_dashboard', user: @user %>


	<!-- Main dashboard -->
	<div class="col-sm-9">
		<!-- Full name -->
		<h1><%= @user.fullname %></h1>
		<h5>Visual, UI, UX Designer</h5>
		<hr>
		<p>
			<a href="#" class="btn btn-success">Follow Rod</a>
			&nbsp;&nbsp;
			<a href="#" class="btn btn-info">Send Message</a>

			<%= link_to edit_user_path(current_user), class: "pull-right" do %> 
			<i class="glyphicon glyphicon-pencil"></i>&nbsp Edit your profile
			<% end %>
		</p>
		<hr> 

		<% if @user.client? %>
		<%= render 'client_tabs', user: @user %>
		<% else %>
		<%= render 'worker_tabs', user: @user %>
		<% end %>


	</div>
	<!--// Main dashboard -->

</div>
<!--// Row -->

app/views/users/show.js.erb
$('#skill_sections').html("<%= j render(:partial => 'users/skill_section', :locals => { skills: @skills }) %>")


$('.article').readmore({
	maxHeight: 80,
	speed: 250,
	moreLink: '<a href="#" class="read-more-link">Read more...</a>',
	lessLink: '<a href="#">Read less</a>'

});

$('.article').readmore();