config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'signup' => 'static_pages#signup'
  get 'registration' => 'users#new'
  get 'login' => 'sessions#new'

  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users do
    member do
      get :clients, :workers
    end
  end
  resources :catalogues do
   collection do
    match 'search' => 'catalogues#search', via: [:get, :post], as: :search
  end
end
resources :tasks do
  resources :responses 
end
resources :responses do
  resources :subcomments
end
resources :appointments
resources :subcomments
resources :educations
resources :offered_services
resources :works
resources :worker_steps
resources :client_steps

end

app/controllers/catalogues_controller.rb
class CataloguesController < ApplicationController

	def search
		index
		render :index
	end

	def index
		@public_posts = @result
	end

end

app/helpers/catalogues_helper.rb
module CataloguesHelper

end

app/views/catalogues/_side_filters.html.erb
<%#******************SIDE FILTERS******************* %>



	<!-- SEARCH FORM -->
	<span id="sql_search"><%= search.result.to_sql%></span>
	<%= search_form_for search, :defaults => {:required => false}, url: url_for(controller: 'catalogues', action: 'index') do |f| %>

	<%#******************Category filter******************* %>
	<div class="panel panel-default">
		<div class="panel-heading text-muted"><h2 class="alignleft"><strong>Category</strong></h2>
		</div>
		<div class="panel-body">

			<!-- CATEGORY RETURN BUTTON -->
			<button style="width:100%" type="button" class="btn btn-default" aria-label="Left Align" id="all-categories"> << All Categories</button>

			<!-- CATEGORY DROP DOWN -->
			<%= f.input :subcategory_category_id_eq, label: "Category", collection: Category.order(:name), label_method: :task_name_and_count, value_method: :id, include_blank: "All categories "%>

			<!-- SUBCATEGORY RETURN BUTTON -->
			<button style="width:100%" type="button" class="btn btn-default" aria-label="Left Align" id="all-subcategories">  </button> 

			<!-- SUBCATEGORY DROPDOWN -->
			<%= f.input :subcategory_id_eq, label: "Subcategory", collection: Category.order(:name), label_method: :task_name_and_count, as: :grouped_select, group_method: :subcategories%>

			<!-- SUBCATEGORY SELECTED ITEM -->
			<div style="margin-top:15px" class="well well-sm text-center" id="subcategory-item" ></div>
		</div>
	</div>


	<%#******************Location filter******************* %>
	<div class="panel panel-default">
		<div class="panel-heading text-muted"><h2 class="alignleft"><strong>Location</strong></h2></i>
		</div>
		<div class="panel-body">
			
			<!-- COUNTY RETURN BUTTON -->
			<button style="width:100%" type="button" class="btn btn-default" aria-label="Left Align" id="all-counties"> << All Counties</button>

			<!-- COUNTY DROP DOWN -->
			<%= f.input :area_county_id_eq, label: "County", collection: County.order(:name), label_method: :task_name_and_count, value_method: :id, include_blank: "All counties "%>

			<!-- AREA RETURN BUTTON -->
			<button style="width:100%" type="button" class="btn btn-default" aria-label="Left Align" id="all-areas">  </button> 

			<!-- AREA DROP DOWN BUTTON -->
			<%= f.input :area_id_eq, label: "Area", collection: County.order(:name), as: :grouped_select, label_method: :task_name_and_count, group_method: :areas %>

			<!-- AREA SELECTED ITEM -->
			<div style="margin-top:15px" class="well well-sm text-center" id="area-item" ></div>

		</div>
	</div>


	<%#******************Pay filter******************* %>
	<div class="panel panel-default">
		<div class="panel-heading text-muted"><h2 class="alignleft"><strong>Pay Offer</strong></h2></div>
		<div class="panel-body">
			<button style="width:100%" type="button" class="btn btn-default" aria-label="Left Align" id="all-pay-types"> << All pay types</button>

			<!-- PAY TYPE DROPDOWN -->
			<%= f.input :is_pay_per_hour_eq_any, as: :select, label: "Pay type", :collection => [['Fixed pay',false],['Pay per hour', true]], label_method: lambda { |t| "#{t[0]} (#{@search.result.to_a.count{|x| x.is_pay_per_hour == t[1]}})"}, include_blank: "All pay type" %>

			<!-- MINIMUM FIELD -->
			<div class="pay-type-label-catalogue" id="minimum-label">Minimum</div>
			<div class="test">	
				<%= f.input :pay_offer_gteq, label: false, wrapper: :horizontal_input_group do %>
				<span class="input-group-addon">€</span>
				<%= f.input_field :pay_offer_gteq, as: :integer, class: "form-control", min: "10" %>	
				<% end %>
			</div>
			<br><br>

			<!-- MAXIMUM FIELD -->
			<div class="pay-type-label-catalogue" id="maximum-label">Maximum</div>
			<div class="test">
				<%= f.input :pay_offer_lteq, label: false, wrapper: :horizontal_input_group do %>
				<span class="input-group-addon">€</span>
				<%= f.input_field :pay_offer_lteq, as: :integer, class: "form-control", min: "10" %>	
				<% end %>
			</div>

			<!-- REFRESH BUTTON -->
			<button type="button" class="btn btn-default btn-xl pull-right" aria-label="Left Align" id="refresh-button">
				<span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>&nbspRefresh
			</button>
			<% end %>
			
		</div>
	</div>

app/views/catalogues/_sort_filters.html.erb
<span class="pull-right">
	<div class="btn-group">
		<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
			Sort by&nbsp&nbsp<span class="caret"></span>
		</button>
		<ul class="dropdown-menu" id= "sort_by" role="menu">
			<li><%= sort_link(search, :pay_offer, 'Pay offer') %></li>
			<li><%= sort_link(search, :created_at, 'Date') %></li>
		</ul>
	</div>
</span>

app/views/catalogues/_task_posts.html.erb
<!-- <li class="list-group-item is_your_post_<%#current_user?(post.client) %>"> -->
<div class="panel panel-default">
	<div class="panel-heading task-post">
		<div class="col-md-6">
			<h4 class="title-heading"><%= link_to post.title, task_path(post.id) %></h4>
		</div>
		<div class="col-md-6">
			<span class="pull-right">OFFERED PAY: &nbsp; <strong>€<%= post.pay_offer%> <%= pay_type(post.is_pay_per_hour)%></strong> </span>
		</div>
	</div>

	<div class="panel-body">

		<div class="row">
			<div class="col-md-7"> 
				
				<div class="row">
					<div class="col-md-2"> 
						<!-- Display picture -->
						<% if post.client.picture? %>
						<%= image_tag post.client.picture.url, class: "img-thumbnail" if user.picture? %><br><br>
						<% else %>
						<%= image_tag 'default.jpg', :size => "90x90", class: "img-thumbnail"  %>
						<br><br>
						<% end %>
					</div>

					<div class="col-md-10"> 
						<h5>Posted by <%= link_to post.client.fullname, user_path(post.client.id) %> <br> Task Location: <%= post.client.area.present? ? post.client.location : "Undefined"  %> </h5>
						
					</div>
					
				</div>
				

				<%= post.description%><br><br>
				Subcategory: <%= post.subcategory.name%> | Posted <%= customised_time_ago_in_words(post.created_at) %> ago 
			</div>

			<div class="col-md-5">
				Task's Appointment Details: <br>
				Start time: <%= post.appointments.last.start_at.strftime("%I:%M %p") %> 
				on <%= post.appointments.last.start_at.strftime("%a, %d %B, %Y") %> <br>
				<% if post.is_pay_per_hour %>
				End time: <%= post.appointments.last.end_at.strftime("%I:%M %p")%> on <%= post.appointments.last.end_at.strftime("%a, %d %B, %Y") %> <br>

				Duration: <%= time_in_hour_and_minutes(post.appointments.last.end_at - post.appointments.last.start_at)  %> <br>

				Estimated total earnings: €<%= calculate_earnings(post.appointments.last.end_at - post.appointments.last.start_at, post.pay_offer)  %>
				<% end %>
			</div>
		</div>
	</div>

</div>

app/views/catalogues/index.html.erb
<% provide(:title, "Catalogue") %>


<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">

		<div class="row">
			<div class="col-lg-4">
				<%= link_to "Instahire", root_path, id: "logo" %>
				<div class="input-group">
					<%= search_form_for @search, url: url_for(controller: 'catalogues', action: 'search'), html: { method: :post }  do |search| %>
					<%= search.input :title_or_description_cont, label: false %>
					<span class="input-group-btn">
						<%= button_tag(type: 'submit', class: "btn btn-primary") do %>
						<span class="glyphicon glyphicon-search">
						</span>
						<% end %>
					</div><!-- /input-group -->
					
				</div><!-- /.col-lg-6 -->
				<nav>
					<ul class="nav navbar-nav pull-right">

						<% if logged_in? %>
						<li><%= link_to "Catalogue", catalogues_path %></li>
						<li><%= link_to "Edit Education", edit_education_path(current_user) %></li>
						<li><%= link_to "Post a task", new_task_path %></li>
						<li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
						<li><%= link_to "Users", users_path %></li>
						<li><%= link_to "Profile", current_user %></li>
						<li><%= link_to "Log out", logout_path, method: "delete" %></li>
						<% else %>
						<li><%= link_to "Sign up", signup_path %></li>
						<li><%= link_to "Log in", login_path %></li>
						<% end %>

					</ul>
				</nav>
			</div><!-- /.row -->
		</div>
	</header>
	<div class="panel panel-default">
		<div class="panel-body" style="max-height:10;">
			<h1 id="filter-result-display"></h1>
		</div>
	</div>

	
	<div class="row">

		<div class="col-sm-3">
			<%= render 'side_filters', search: @search %>
		</div>

		<div class="col-sm-9">

			<ul class="nav nav-tabs id"="myTab">
				<li class="active"><a href="#public_post" data-toggle="tab">Public posts</a></li>
				<li class="active"><a href="#global_post" data-toggle="tab">Followers posts</a></li>

				<%= render 'sort_filters', search: @search %>

			</ul>



			<div class="tab-content">




				<div class="tab-pane active" id="public_post">
					<%= @search.result.to_sql%>
					<% @public_posts.each do |post| %>
					<br>
					
					<%= render 'task_posts', post: post %>
					<% end %>

					<hr>
				</div><!--/tab-pane -->

			</div>
		</div>

	</div>
	<% end %>